apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dyndns
resources:
  - ../../base
patches:
  - target:
      version: v1
      kind: ConfigMap
      name: dyndns-config
    path: configmap-patch.yaml
