apiVersion: batch/v1
kind: CronJob
metadata:
  name: dyndns
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          containers:
          - name: dyndns
            image: politeauthority/dyndns:0.0.1
            imagePullPolicy: Always
            env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: dynsdns-config
                  key: redis-host
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: dynsdns-config
                  key: redis-db
            - name: REDIS_PASS
              value: "redis-password"
            - name: DOMAIN_FILE
              value: "/config/domains.json"
            - name: FORCE_UPDATE
              valueFrom:
                configMapKeyRef:
                  name: dynsdns-config
                  key: force-update
            - name: NOTIFY_URL
              valueFrom:
                secretKeyRef:
                  name: notification-creds
                  key: NOTIFY_URL
            - name: NOTIFY_PASS
              valueFrom:
                secretKeyRef:
                  name: notification-creds
                  key: NOTIFY_PASS
            volumeMounts:
            - name: domain-config
              mountPath: /config
            command:
              - python3
              - /app/dyndns.py
          restartPolicy: OnFailure
          volumes:
            - name: domain-config
              secret:
                secretName: domain-config
