apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dyndns
resources:
  - deployment.yaml
images:
  - name: harbor.squid-ink.us/politeauthority/dyndns
    newTag: 0.0.2-dev-5
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: harbor.squid-ink.us/politeauthority/dyndns:0.0.2-dev

  # - target:
  #     kind: CronJob
  #   patch: |-
  #     - op: replace
  #       path: /spec/jobTemplate/spec/template/spec/containers/0/image
  #       value: harbor.squid-ink.us/politeauthority/dyndns:0.0.1
  # - target:
  #     kind: CronJob
  #   patch: |-
  #     - op: add
  #       path: /spec/jobTemplate/spec/template/spec/imagePullSecrets
  #       value: [{ name: harbor }]
  # - target:
  #     version: v1
  #     kind: ConfigMap
  #     name: dynsdns-config
  #   path: patch-configmap.yaml
