apiVersion: batch/v1
kind: Job
metadata:
  name: dyndns-force
spec:
  template:
    spec:
      containers:
      - name: dyndns-force
        image: politeauthority/dyndns:0.0.5
        command:
        - python3
        - /app/dyndns.py
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: dynsdns-config
              key: redis-host
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: dynsdns-config
              key: redis-db
        - name: REDIS_PASS
          value: "redis-password"
        - name: DOMAIN_FILE
          value: "/config/domains.json"
        volumeMounts:
        - name: domain-config
          mountPath: /config
      restartPolicy: Never
      volumes:
        - name: domain-config
          secret:
            secretName: domain-config
  backoffLimit: 2
  