apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dyndns
resources:
  - ../../base
  - sealed-secret-domains.yaml
  - sealed-secret-notification.yaml
patches:
  # Pull from docker hub for now
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/image
        value: politeauthority/dyndns:0.0.5
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/-
        value:
          name: QUIGLEY_API_BASIC_AUTH
          valueFrom:
            secretKeyRef:
              name: notification-creds
              key: QUIGLEY_API_BASIC_AUTH
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/-
        value:
          name: QUIGLEY_API_ROOM
          valueFrom:
            secretKeyRef:
              name: notification-creds
              key: QUIGLEY_API_ROOM
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/-
        value:
          name: QUIGLEY_API_URL
          valueFrom:
            secretKeyRef:
              name: notification-creds
              key: QUIGLEY_API_URL
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/imagePullSecrets
        value: [{ name: docker-hub }]
  - target:
      version: v1
      kind: ConfigMap
      name: dyndns-config
    patch: |-
      - op: replace
        path: /data/redis-host
        value: redis.q-redis.svc.cluster.local
