apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dyndns
resources:
- ../../base
- sealed-secret-domains.yaml
patches:
 - target:
      version: v1
      kind: ConfigMap
      name: dynsdns-config
   path: configmap-patch.yaml
