name: Stage Push

on:
  push:
    branches: 
      - cicd

jobs:
	build:
		uses: ./.github/workflows/build.yaml
    needs: validate
		secrets: inherit
		permissions:
			pull-requests: read
			contents: read
		with:
			cicd-version: "${{ vars.CICD_VERSION }}"
			harbor-user: "${{ vars.HARBOR_USER }}"
      tag-name: "dev"
